[package]
name = "plain_enum"
version = "0.9.0"
authors = ["philipp <philipp>"]
description = "Mimicing Java's enum::values() and EnumMap"
license = "MIT/Apache-2.0"
repository = "https://github.com/phimuemue/rs_plain_enum"
documentation = "https://docs.rs/plain_enum"

[dependencies]
